### ISSUE TITLE
Request: HACS Compatibility

### ISSUE THREAD

**Issue by brianhanifin** [rr326/ha_ll_notify#1]
I think this could be a very useful integration. I just think you haven't got much feedback because it isn't available on the HACS store. If you were able to convert this to be installable from the HACS store, I think this could be a popular integration!

Here is some more information about that:
https://github.com/custom-components/information
https://github.com/custom-components/integration_blueprint

**Comment by rr326** [comment]
@brianhanifin Thanks for the idea. I may try that, though I'll admit I'm reluctant to throw good time after bad. But if I get some free time and the process doesn't seem onerous, I'll give it a try. Thanks Brian.
