### ISSUE TITLE
Not working with Home Assistant limited app on Android?

### ISSUE THREAD

**Issue by igreg** [rr326/ha_ll_notify#4]
I am trying to make it work with my Fire HD 8 tablet, but can't see the notification on the device.
It works fine on my iPhone and browse. I'm using the full version of the mobile app available on Google Play (which is more up-to-date).

Any idea why it's not working on Android?

**Comment by rr326** [comment]
Maybe try the same browser on a computer and see if it fails? If so, try the developer console. Also maybe try forcing a full reload if you can. 

i have an android device and it works normally. 

Can you do chrome on your fire?

**Comment by rr326** [comment]
One other idea - check out the website for [Alertify JS](https://alertifyjs.com).

ll_notify is a Home Assistant wrapper on Alertly. So if it's not working, that's a good place to look.
